### ISSUE TITLE
IntelliJ plugin

### ISSUE THREAD

**Issue by thedrow** [KusionStack/KCLVM#364]
## Feature Request

**Is your feature request related to a problem? Please describe:**
In order to develop KCL based configurations more efficiently, I'd like to have autocompletion and building integrated into my IDE. In addition, I'd like to be able to immediately review errors so I can fix them.
Right now, developing KCL configurations using a text editor is error-prone to typos and schema validation failures which will only be reported after using the KCL compiler from the terminal.

**Describe the feature you'd like:**
I'd like to have an IntelliJ plugin I can install and use for development of KCL based projects.

**Describe alternatives you've considered:**
I use IntelliJ but a plugin for VSCode will also be useful.

**Teachability, Documentation, Adoption, Migration Strategy:**
Users would install the KCL plugin and be able to build KCL projects from IntelliJ.

**Comment by Peefy** [comment]
Hello, @thedrow. Thanks for your feature request. We have provided two simple kinds of plugins for KCL. You can get more help information at the following link:

* IntelliJ Plugin: https://github.com/KusionStack/intellij-kcl
* VSCode Plugin: https://github.com/KusionStack/vscode-kcl

If you have any questions, feel free to ask us. In addition, can you tell us what you use KCL for and what more issues you have encountered? cc @amyXia1994

**Comment by thedrow** [comment]
I'm just evaluating the technology for now.
Is there a plan to release the plugin so it will be able to be installed from the JetBrains marketplace?

**Comment by amyXia1994** [comment]
Hi, @thedrow  Welcome! We are glad to hear that you are adopting KCL in your development. And for the plugin support, as mentioned by @Peefy kusion now provides IDE plugins on both VS Code and Intellij IDEA:

- For VS Code: please search the VS Code Extension Market and install the [extension for Coding with KCL Language](https://marketplace.visualstudio.com/items?itemName=kcl.kcl-vscode-extension) and [the extension for Operation with Kusion](https://marketplace.visualstudio.com/items?itemName=KusionStack.kusion). The Extensions now support syntax highlighting, code navigation, hover, auto-completion on keywords and snippets, and configuration outline. 

-  For Intellij IDEA: the KCL plugin is not released publicly yet, and the release is coming soon. For now the IDEA 2020.2-2022.2 are supported. And the plugin now supports syntax highlighting, code navigation, and simple auto-completion on keywords and snippets. I'm working on it and once released I'll make sure to remind you. 

- And KCL coding on the GitHub web IDE -- GitHub Codespaces is also supported. The features are the same as the extensions on the VS Code, but free from the Kusion installation. This [guide](https://kusionstack.io/docs/user_docs/getting-started/cloudide) shows how to use kusion and KCL within a codespace.

Both plugins are under development, but currently, we are more focused on and actively developing the VS Code extension. Could you please provide more information about the how you use KCL, so that we can promote more targeted development for the Intellij-kcl plugin?

By the way, welcome to join the Kusion [slack](https://kusionstack.slack.com/join/shared_invite/zt-19lqcc3a9-_kTNwagaT5qwBE~my5Lnxg#/shared-invite/email) for more intimate communication. 🤝
