### ISSUE TITLE
cargo update breaks build

### ISSUE THREAD

**Issue by thinkrapido** [KusionStack/KCLVM#398]
Bug Report
1. Minimal reproduce step (Required)
checkout: 8ed4c5e (HEAD -> main, tag: v0.4.4, origin/main, origin/HEAD) Feat(kclvm-win): remove the "kclvm.requirements.done.txt" on windows. (#392)

perform cargo update in ROOT/kclvm folder

2. What did you expect to see? (Required)
Build finishs

3. What did you see instead (Required)
Issues with compiler because some dependecies, like inkwell don't fit anymore
The build finishes with errors

4. What is your KusionStack components version? (Required)
8ed4c5e (HEAD -> main, tag: v0.4.4, origin/main, origin/HEAD) Feat(kclvm-win): remove the "kclvm.requirements.done.txt" on windows. (#392)

**Comment by Peefy** [comment]
@thinkrapido Thank you for your feedback. Are you willing to fix it? Or I'll fix it later.

**Comment by thinkrapido** [comment]
I'll go for it. Will take until next week.

BTW. Your Project is awesome and I started a nice sub project: 
https://github.com/i-think-rapido/kcl-loader-rs

**Comment by Peefy** [comment]
> I'll go for it. Will take until next week.
> 
> BTW. Your Project is awesome and I started a nice sub project: https://github.com/i-think-rapido/kcl-loader-rs

Thank you for your praise. This KCL-based schema loader project looks attractive. I hope we can work together for a long time. I have already started and forked it on https://github.com/i-think-rapido/kcl-loader-rs.

In addition, I submitted a quick fix PR for this issue here: https://github.com/KusionStack/KCLVM/pull/399
